boostorg/iostreams

- test/detail/operation_sequence.hpp
"Suppress" is spelled with two P's, even in British English.
> Correct spelling of "suppress"

- build/Jamfile.v2
This makes it so that there's a proper configuration check for bzip2 like there is for zlib. bzip tool is in another pull request: https://github.com/boostorg/build/pull/112
New config check for zlib happened to work a lot better for me than old Jamfile code when building with mingw toolset. Unfortunately it was zlib only change and I need bzip support too, so I made those pull requests.
> Made boost.iostreams Jamfile use proper bzip2 tool

- include/boost/iostreams/detail/is_dereferenceable.hpp
Undo use of
*boost/type_traits/detail/bool_trait_def.hpp* and *boost/type_traits/detail/template_arity_spec.hpp*,
Since, use of these header is deprecated.
> Fix for Ticket #11860

- include/boost/iostreams/detail/config/unreachable_return.hpp
Remove misleading comment about Boost.Exception.
> Remove misleading comment

- src/file_descriptor.cpp
- test/detail/verification.hpp
- test/read_input_istream_test.hpp
- silenced narrowing conversion warnings with explicit casts
- fixed a variable shadowing warning by removing an unused variable
> Fix MSVC compiler warnings

- include/boost/iostreams/chain.hpp
- Some of the functionality including size() have been moved to class chain_client in chain.hpp hence the fix in chain.hpp
> #10072. Fixed filtering_stream::size() is not const.

- include/boost/iostreams/filter/bzip2.hpp
- include/boost/iostreams/filter/gzip.hpp
- include/boost/iostreams/filter/zlib.hpp
This patch renames some constructor parameters to avoid shadow warning.
> fix shadow warnings from clang trunk

- include/boost/iostreams/detail/config/fpos.hpp
Included VxWorks as one of the platforms that do not use std::fpos from the Dinkumware Standard Library. This will allow it to compile properly on VxWorks.
> Included VxWorks as one of the platforms that do not use Dinkumware Standard Library

- src/zlib.cpp
- test/gzip_test.cpp
This fixes a problem where the gzip_decompressor would fail the CRC
check when reading a multipart gzip file that had been written using
Z_FULL_FLUSH, and contains an empty part (with a 0 CRC).
Including a unit test that exposes the bug.
> Do not check length_ before computing CRC.

- include/boost/iostreams/device/null.hpp
basic_null_device::read returns 0 but -1 is expected.
Modified return status to -1.
> Ticket #11752. Modified return status to return -1

- include/boost/iostreams/code_converter.hpp
- include/boost/iostreams/filter/bzip2.hpp
- include/boost/iostreams/filter/gzip.hpp
- include/boost/iostreams/filter/symmetric.hpp
- include/boost/iostreams/filter/zlib.hpp
- src/file_descriptor.cpp
- src/zlib.cpp
zlib: recover Z_BUF_ERROR conditions
file_descriptor: openmode compatibility to C++ standard
> bugs in file_descriptor and gzip-zlib-bzip2 filters

- doc/installation.html
Removed at 08798f6.
Question: how to configure with zlib support, see https://svn.boost.org/trac/boost/ticket/12505.
> Undocument ZLIB_* BZIP2_* deleted b2 variables

- include/boost/iostreams/detail/config/dyn_link.hpp
The symbol visibility settings are only set for Win/gcc builds. Added equivalent instructions that will work for Mac OS/Clang builds. This is similar to what was done in the config files of the other Boost libraries.
> Fix hidden visibility symbols for mac/clang

- include/boost/iostreams/filter/gzip.hpp
`warning: implicit conversion from 'const int' to 'char' changes value from 139 to -117 [-Wconstant-conversion]`
> Silence signedness warning in clang

- include/boost/iostreams/filter/gzip.hpp
Avoids:
warning: overflow in implicit constant conversion
Ideally the casts should be completely avoided, since when char is
signed, half of them including this one actually trigger undefined
behaviour, i.e. this code is very broken, but there doesn't seem to
be an easy fix for that.
> gzip: Add cast to avoid compiler warning.

- include/boost/iostreams/filter/lzma.hpp
- src/lzma.cpp
- test/lzma_test.cpp
As git history isn't useful in this case, it might be good
to add more details in the header instead.
As mentioned in https://github.com/boostorg/iostreams/pull/38.
Honestly no idea this is best-practice, but it seems to me to clarify things while still keeping all possibly applicable copyright notices intact.
> Clarify origin and authors of recently added files.

- src/bzip2.cpp
- src/zlib.cpp
5c9bde1d0a6460f03f10b3e203057d525f09745c forgot to also update
the .cpp files.
> Update cpp files for removed MSVC workarounds.

- include/boost/iostreams/stream.hpp
The workaround in VC++ CRT of MSVC compiler bug leads to the fact that if your class inherits from std streams you will get C4250 warning. (https://connect.microsoft.com/VisualStudio/feedback/details/733720/)
```
..\..\..\..\boost/iostreams/stream.hpp(145) : warning C4250: 'boost::iostreams::stream<Device>' : inherits 'std::basic_istream<_Elem,_Traits>::std::basic_istream<_Elem,_Traits>::_Add_vtordisp1' via dominance
..\..\..\..\boost/iostreams/stream.hpp(145) : warning C4250: 'boost::iostreams::stream<Device>' : inherits 'std::basic_ostream<_Elem,_Traits>::std::basic_ostream<_Elem,_Traits>::_Add_vtordisp2' via dominance
```
If you are not fine with this fix, will it be okay to suppress it like that https://github.com/Kojoley/iostreams/commit/ba61a0c1c376e89617a09ff171964a317bb7f236?
> Fix C4250 warning because of VS2012 CRT

- include/boost/iostreams/detail/buffer.hpp
- include/boost/iostreams/filter/bzip2.hpp
- include/boost/iostreams/filter/lzma.hpp
- include/boost/iostreams/filter/zlib.hpp
Replace them by their cousins from std::allocator_traits.
Signed-off-by: Daniela Engert <dani@ngrt.de>
> Most members of std::allocate are deprecated in C++17

- include/boost/iostreams/detail/config/fpos.hpp
The Dinkum code base that's distributed with VxWorks and QNX  is slightly different than Windows and this seems to be one of the differences.
> VxWorks' Dinkum clib does not support the fpos extension

- test/Jamfile.v2
Do not try to run tests when the dependencies
are not available.
Should fix the AppVeyor build.
> Fix test when zlib or bzip2 not available.

- build/Jamfile.v2
- doc/bibliography.html
- doc/installation.html
- include/boost/iostreams/filter/zstd.hpp
- src/zstd.cpp
- test/Jamfile.v2
- test/zstd_test.cpp
Implements trac issue #13356.
Not tested in real production use, help welcome.
Depends on "build" PR that adds zstd.jam (though it is just a search-and-replace of lzma.jam)
> Add zstd compression/decompression filter.

- include/boost/iostreams/filter/bzip2.hpp
- src/bzip2.cpp
When error is encounted during compression/decompression exception is
thrown (through bzip2::check()) but memory associated with the bzip2 stream
wasn't properly released (BZ2_bzCompressEnd()/BZ2_bzDecompressEnd() must be
called to do that - which is done by calling bzip2_base::end()).
As end() throws on error, and we are now calling end() in destructor, nothrow
version needed to be made so we don't terminate user program in case end()
fails.
> Fixed bzip2 memory leak.

- include/boost/iostreams/detail/adapter/non_blocking_adapter.hpp
- test/Jamfile.v2
- test/read_nonblocking_test.cpp
Non-blocking adapter read() wasn't tracking amount read properly which
could cause an infinite loop when underlying (infinite) source returns amounts
smaller than requested. Also amounts read previously were
overwritten by subsequent calls.
> Fixed non-blocking adapter read() data overwrite and infinite loop.

- include/boost/iostreams/detail/config/fpos.hpp
Boost is attempting to use a function not in the standard, seekpos(),
guarded by this setting. Looks like Boost can use the standards
conforming interface for MSVC++ instead. It should work going
back effectively "forever" as far as MSVC++ is concerned, but this
guard applies the change only to 2017. It's possible there is a better
control in boost.config I missed.
> Turn off BOOST_IOSTREAMS_HAS_DINKUMWARE_FPOS for MSVC++

- include/boost/iostreams/detail/restrict_impl.hpp
fixes msvc warning C5032: "detected #pragma warning(push) with no corresponding #pragma warning(pop)"
> add missing warning re-enabling include

- include/boost/iostreams/filter/bzip2.hpp
- test/bzip2_test.cpp
> Fix processing of multi-stream files

- include/boost/iostreams/filter/lzma.hpp
- src/lzma.cpp
- test/lzma_test.cpp
Enables multithreaded LZMA compression in Boost.iostreams.
I have tested the build and behavior on a range of Ubuntu and RHEL systems. I have tested the build and behavior of all numbered liblzma release versions in their git repo.
Unit testing doesn't cover:
- That multiple threads are actually used when appropriate. Because how would I do that in a unit test?
- Behavior on larger amounts of data (which liblzma deploys more threads on). Because it would slow down the execution of tests significantly.
- That the build correctly detects liblzma's capabilities. Because this is a build issue.
- That the build correctly uses BOOST_IOSTREAMS_LZMA_NO_MULTITHREADED macro. Because this is a build issue.
> LZMA threads

- include/boost/iostreams/detail/adapter/range_adapter.hpp
The warnings are generated by `boost/detail/iterator.hpp`, which has been deprecated in favor of `<iterator>`.
Also, updated location of `enable_if.hpp`.
> Avoid using deprecated headers to silence compiler warnings

- include/boost/iostreams/detail/enable_if_stream.hpp
This patch makes the header able to be built standalone, making possible C++ clang modules builds.@vgvassilev
> Add missing include

- include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp
This resolves a warning in Visual Studio which is currently prevents using `boost::iostreams::stream<>` when this warning is enabled.
What seems to happen is that the first part of the expression is recognized as constant, but somehow the second part is not taken into account to see that the expression as a whole is not constant. Flipping the two around fixes the warning, but not the problem. In principle this code should still trigger the warning, because you probably want to know when a sub-expression in an if() statement is constant too. Because a constant sub-expression seems just as wrong a a constant full expression.
However, this seems to solve the warning without any changes to the logic, so this is a simple fix for now.
> Resolve visual studio warning C4127: conditional expression is constant.

- include/boost/iostreams/filter/newline.hpp
Unlike gcc/clang, the extra parentheses don't silence MSVC's warning about assignments within conditional statements, and the latest MSVC 2019 issues warnings on these lines. This change performs the assignments prior to the "if" statements.
> MSVC "assignment within conditional" warning fix

- test/detail/utf8_codecvt_facet.cpp
This change fixes a buffer overflow in the UTF-8 codecvt facet's `do_length` function that was detected by MSVC's AddressSanitizer when running tests internally. Prior to this change, the character pointed to by `from_end`, which may point to invalid memory, was being dereferenced. The fix is to modify the loop to only dereference a character when we know we haven't yet reached `from_end`.
> Fixing buffer overflow in do_length

- include/boost/iostreams/filter/gzip.hpp
Removes shadow-field warnings by adding an underscore as suffix as already done for other parameters of the affected constructor.
warning: parameter 'level' shadows member inherited from type 'zlib_params' [-Wshadow-field]
gzip_params( int level              = gzip::default_compression,
> Remove shadow-field warnings.

- include/boost/iostreams/filter/zstd.hpp
This MR fixes two typos in the comment for `zstd_decompressor_impl` in `include/boost/iostreams/filter/zstd.hpp`.
> Fix typos in zstd_decompressor_impl comment

- include/boost/iostreams/detail/config/disable_warnings.hpp
This warning has been observed under more than one version. One specific example, as described in issue #138, is on indirect_streambuf.hpp(440) when Whole Program Optimization is off. In this case, the line before is seen by the optimizer as always throwing for particular instantiations of the template, and therefore the line in question is flagged as not reachable.
MSVC team has stated this is is expected behavior. (https://developercommunity.visualstudio.com/t/Unexpected-C4702-Unreachable-code-in-boo/10410775)
This is a simple and hopefully good-enough fix.
> Disable msvc warning that can occur under some versions+settings

- CMakeLists.txt
- Introduce CACHE variables for ZLIB, BZip2, LibLZMA, and Zstd targets
- Update boost_iostreams_option function calls to use new variables
> CMake: Add customizable target names for compression libraries
